@startuml

title Сравнение классической модели БД с документальной на примере сервиса 'Заявка на перевозку'
hide empty members

package "Реляционное хранение" <<database>> #F0FFFF{
    !include request-data-rel-er.puml
}

package "Хранение объектов в JSON-столбцах" <<database>> #F0FFFF {
    !include request-data-json.puml
    !include request-data-er.puml

    TRANSPORT_REQUEST::data .[#blue,thickness=3]right.# dto : //полный JSON-объект//

}

TRANSPORT_REQUEST .down. yms_transportation_request
dto .down. yms_transportation_goal
dto .down. yms_transportation_request_candidate
dto .down. yms_expected_set_type
note bottom of yms_transportation_request_history: Хранится в **BPM**
note bottom of yms_transportation_request_file: Хранится в **S3**
note bottom of yms_transportation_request_comment: Отдельный сервис

@enduml